# Generated by Django 5.2.13 on 2026-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_notification_updated_at_and_postlike_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='postlike',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
