# Generated by Django 3.1.12 on 2026-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20260417_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='liker_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='postlike',
            name='liker_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
