# Generated by Django 5.2 on 2026-04-18

from django.db import migrations, models
from django.utils.text import slugify


def fill_category_slugs(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    for cat in Category.objects.all().order_by("id"):
        root = slugify(cat.name) or "category"
        candidate = root
        n = 1
        while Category.objects.filter(slug=candidate).exclude(pk=cat.pk).exists():
            candidate = f"{root}-{n}"
            n += 1
        cat.slug = candidate
        cat.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20260417_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.RunPython(fill_category_slugs, noop),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
