from django.urls import path

from .views import (
    CategoryDetailView,
    CategoryListCreateView,
    CategoryPostsBySlugView,
    CommentDetailView,
    ContactMessageDetailView,
    ContactMessageListCreateView,
    GenerateBlogPostView,
    NewsletterReviewDetailView,
    NewsletterReviewListCreateView,
    NewsletterSubscribeView,
    NewsletterSubscriberDetailView,
    NotificationListView,
    NotificationReadAllView,
    NotificationMarkReadView,
    NotificationReadView,
    PostLikeStatusView,
    PostLikeToggleView,
    PostLikesListView,
    PostCommentListCreateView,
    PostDetailView,
    PostListCreateView,
    PostRecommendationsView,
    PostSearchView,
    PostUserLikeStatusView,
    PostUserLikeToggleView,
    PostViewsAnalyticsView,
)

urlpatterns = [
    path("generate-post", GenerateBlogPostView.as_view()),
    path("generate-post/", GenerateBlogPostView.as_view()),
    path("contact/<int:pk>", ContactMessageDetailView.as_view()),
    path("contact/<int:pk>/", ContactMessageDetailView.as_view()),
    path("contact", ContactMessageListCreateView.as_view()),
    path("contact/", ContactMessageListCreateView.as_view()),
    path("newsletter-reviews/<int:pk>", NewsletterReviewDetailView.as_view()),
    path("newsletter-reviews/<int:pk>/", NewsletterReviewDetailView.as_view()),
    path("newsletter-reviews", NewsletterReviewListCreateView.as_view()),
    path("newsletter-reviews/", NewsletterReviewListCreateView.as_view()),
    path("newsletter/<int:pk>", NewsletterSubscriberDetailView.as_view()),
    path("newsletter/<int:pk>/", NewsletterSubscriberDetailView.as_view()),
    path("newsletter", NewsletterSubscribeView.as_view()),
    path("newsletter/", NewsletterSubscribeView.as_view()),
    path("analytics/post-views", PostViewsAnalyticsView.as_view()),
    path("analytics/post-views/", PostViewsAnalyticsView.as_view()),
    path("search", PostSearchView.as_view()),
    path("search/", PostSearchView.as_view()),
    path("categories/<slug:slug>/posts", CategoryPostsBySlugView.as_view()),
    path("categories/<slug:slug>/posts/", CategoryPostsBySlugView.as_view()),
    path("categories/<int:pk>", CategoryDetailView.as_view()),
    path("categories/<int:pk>/", CategoryDetailView.as_view()),
    path("categories", CategoryListCreateView.as_view()),
    path("categories/", CategoryListCreateView.as_view()),
    path("posts/<str:post_key>", PostDetailView.as_view()),
    path("posts/<str:post_key>/", PostDetailView.as_view()),
    path("posts/<slug:slug>/recommendations", PostRecommendationsView.as_view()),
    path("posts/<slug:slug>/recommendations/", PostRecommendationsView.as_view()),
    path("posts", PostListCreateView.as_view()),
    path("posts/", PostListCreateView.as_view()),
    path("posts/<int:post_id>/comments", PostCommentListCreateView.as_view()),
    path("posts/<int:post_id>/comments/", PostCommentListCreateView.as_view()),
    path("posts/<int:post_id>/like", PostLikeToggleView.as_view()),
    path("posts/<int:post_id>/like/", PostLikeToggleView.as_view()),
    path("posts/<int:post_id>/like-status", PostLikeStatusView.as_view()),
    path("posts/<int:post_id>/like-status/", PostLikeStatusView.as_view()),
    path("posts/<int:post_id>/likes", PostLikesListView.as_view()),
    path("posts/<int:post_id>/likes/", PostLikesListView.as_view()),
    path("posts/<int:post_id>/user-like", PostUserLikeToggleView.as_view()),
    path("posts/<int:post_id>/user-like/", PostUserLikeToggleView.as_view()),
    path("posts/<int:post_id>/user-like-status", PostUserLikeStatusView.as_view()),
    path("posts/<int:post_id>/user-like-status/", PostUserLikeStatusView.as_view()),
    path("comments/<int:pk>", CommentDetailView.as_view()),
    path("comments/<int:pk>/", CommentDetailView.as_view()),
    path("notifications", NotificationListView.as_view()),
    path("notifications/", NotificationListView.as_view()),
    path("notifications/mark-read", NotificationMarkReadView.as_view()),
    path("notifications/mark-read/", NotificationMarkReadView.as_view()),
    path("notifications/read-all", NotificationReadAllView.as_view()),
    path("notifications/read-all/", NotificationReadAllView.as_view()),
    path("notifications/<int:pk>/read", NotificationReadView.as_view()),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view()),
    
]
